name: CI for Jammini

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python environment for Backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Backend Dependencies
        working-directory: backend
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      # 3. Set Environment Variables
      - name: Set Environment Variables
        run: |
          echo "DB_NAME=test_db" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PWD=postgres" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV

      # 4. Run Backend Tests
      - name: Run Backend Tests
        working-directory: backend
        run: |
          source env/bin/activate
          python manage.py test

      # 5. Notify of Successful CI
      - name: Notify Success
        if: success()
        run: echo "✅ CI Pipeline Completed Successfully! 🎉"
